### Get requewst to get JWT token from DevAuthConfig
GET http://localhost:8080/dev

> {%
    client.global.set("auth_token", response.body.token);
%}

### GET books
GET http://localhost:8080/api/books
Authorization: Bearer {{auth_token}}

### GET members
GET http://localhost:8080/api/members
Authorization: Bearer {{auth_token}}

### GET health no authorisation
GET http://localhost:8080/api/health

###