### GET request to example server
GET http://localhost:8080/api/books
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJkZXYtbG9jYWwiLCJzdWIiOiJtMSIsImV4cCI6MTc2NjgzMTcyMiwiaWF0IjoxNzY2ODI4MTIyfQ.NDToKWF3cJ3yHwAEHO1tRhpFZkmyH6973tSxl0IE1mvq8gt8Elh-_jJPiUplkSV36SKnb3Tz308LCE4YMDvxjcdqzz394f-X1SgGolxh0bD3qcurNGDlIHyeNw1S42ZMURIztM3mXyid0fARo_yuQ3jLBJH9BAemaxTMfFHehUsxzYv1b2lQaSFTGAmskXvLVm2AyR6FAwKK8ilmMceHdAo2pC2LALP9cK7CFxInPN8quIhMi8z8qJCrUM4mAtrylwrD2IxgaHqwkKEKfgX6jo1varF-WzVV_uC7JoyH_yT-8j1JnO1HbHENubhyDdZvbmu-b4mWRDo2COdnlzXU6g

###